---

- name: Download Ollama installation script
  get_url:
    url: "{{ providers.ollama.installer.url }}"
    dest: "/tmp/{{ providers.ollama.installer.destination }}"
    mode: '0755'
  become: yes

- name: Run Ollama installation script
  command: "/tmp/{{ providers.ollama.installer.destination }}"
  become: yes
