---

- name: Download Ollama installation script
  get_url:
    url: "{{ providers.ollama.installer_script_url }}"
    dest: "/tmp/{{ providers.ollama.local_script_name }}"
    mode: '0755'
  become: yes

- name: Run Ollama installation script
  command: "/tmp/{{ providers.ollama.local_script_name }}"
  become: yes
