---

- name: Copy start script to destination server
  template: 
    src: "{{ servers.anythingllm.start_script.local_path }}"
    dest: "/tmp/{{ servers.anythingllm.start_script.destination }}"
    mode: "0755"
    force: yes
  become: true

- name: Run AnythingLLM start script
  command: "/tmp/{{ servers.anythingllm.start_script.destination }}"
  become: yes
