---

- name: Copy stop script to destination server
  template: 
    src: "{{ servers.anythingllm.stop_script.local_path }}"
    dest: "/tmp/{{ servers.anythingllm.stop_script.destination }}"
    mode: "0755"
    force: yes
  become: true

- name: Run AnythingLLM stop script
  command: "/tmp/{{ servers.anythingllm.stop_script.destination }}"
  ignore_errors: yes
  become: yes
